export const LIST_APPRAISALS = 'LIST_APPRAISALS';
export const LIST_APPRAISALS_SUCCESS = 'LIST_APPRAISALS_SUCCESS';
export const LIST_APPRAISALS_FAILURE = 'LIST_APPRAISALS_FAILURE';
export const CREATE_APPRAISALS = 'CREATE_APPRAISALS';
export const CREATE_APPRAISALS_SUCCESS = 'CREATE_APPRAISALS_SUCCESS';
export const CREATE_APPRAISALS_FAILURE = 'CREATE_APPRAISALS_FAILURE';
export const EDIT_APPRAISALS = 'EDIT_APPRAISALS';
export const EDIT_APPRAISALS_SUCCESS = 'EDIT_APPRAISALS_SUCCESS';
export const EDIT_APPRAISALS_FAILURE = 'EDIT_APPRAISALS_FAILURE';
export const DELETE_APPRAISALS = 'DELETE_APPRAISALS';
export const DELETE_APPRAISALS_SUCCESS = 'DELETE_APPRAISALS_SUCCESS';
export const DELETE_APPRAISALS_FAILURE = 'DELETE_APPRAISALS_FAILURE';
export const SHOW_APPRAISAL = 'SHOW_APPRAISAL';
export const SHOW_APPRAISAL_SUCCESS = 'SHOW_APPRAISAL_SUCCESS';
export const SHOW_APPRAISAL_FAILURE = 'SHOW_APPRAISAL_FAILURE';


export const HANDLE_APPRAISAL_CHANGE = 'HANDLE_APPRAISAL_CHANGE';
export const SET_APPRAISAL_DEFAULTS = 'SET_APPRAISAL_DEFAULTS';
export const RESET_APPRAISAL_FIELDS = 'RESET_APPRAISAL_FIELDS';
export const VALIDATE_APPRAISAL_FORM='VALIDATE_APPRAISAL_FORM';