export const LIST_HOLIDAYS = 'LIST_HOLIDAYS';
export const LIST_HOLIDAYS_SUCCESS = 'LIST_HOLIDAYS_SUCCESS';
export const LIST_HOLIDAYS_FAILURE = 'LIST_HOLIDAYS_FAILURE';
export const CREATE_HOLIDAYS = 'CREATE_HOLIDAYS';
export const CREATE_HOLIDAYS_SUCCESS = 'CREATE_HOLIDAYS_SUCCESS';
export const CREATE_HOLIDAYS_FAILURE = 'CREATE_HOLIDAYS_FAILURE';
export const EDIT_HOLIDAYS = 'EDIT_HOLIDAYS';
export const EDIT_HOLIDAYS_SUCCESS = 'EDIT_HOLIDAYS_SUCCESS';
export const EDIT_HOLIDAYS_FAILURE = 'EDIT_HOLIDAYS_FAILURE';
export const DELETE_HOLIDAYS = 'DELETE_HOLIDAYS';
export const DELETE_HOLIDAYS_SUCCESS = 'DELETE_HOLIDAYS_SUCCESS';
export const DELETE_HOLIDAYS_FAILURE = 'DELETE_HOLIDAYS_FAILURE';
export const SHOW_HOLIDAY = 'SHOW_HOLIDAY';
export const SHOW_HOLIDAY_SUCCESS = 'SHOW_HOLIDAY_SUCCESS';
export const SHOW_HOLIDAY_FAILURE = 'SHOW_HOLIDAY_FAILURE';


export const HANDLE_HOLIDAY_CHANGE = 'HANDLE_HOLIDAY_CHANGE';
export const SET_HOLIDAY_DEFAULTS = 'SET_HOLIDAY_DEFAULTS';
export const RESET_HOLIDAY_FIELDS = 'RESET_HOLIDAY_FIELDS';
export const VALIDATE_HOLIDAY_FORM='VALIDATE_HOLIDAY_FORM';