export const LIST_LEAVES = 'LIST_LEAVES';
export const LIST_LEAVES_SUCCESS = 'LIST_LEAVES_SUCCESS';
export const LIST_LEAVES_FAILURE = 'LIST_LEAVES_FAILURE';
export const CREATE_LEAVES = 'CREATE_LEAVES';
export const CREATE_LEAVES_SUCCESS = 'CREATE_LEAVES_SUCCESS';
export const CREATE_LEAVES_FAILURE = 'CREATE_LEAVES_FAILURE';
export const EDIT_LEAVES = 'EDIT_LEAVES';
export const EDIT_LEAVES_SUCCESS = 'EDIT_LEAVES_SUCCESS';
export const EDIT_LEAVES_FAILURE = 'EDIT_LEAVES_FAILURE';
export const DELETE_LEAVES = 'DELETE_LEAVES';
export const DELETE_LEAVES_SUCCESS = 'DELETE_LEAVES_SUCCESS';
export const DELETE_LEAVES_FAILURE = 'DELETE_LEAVES_FAILURE';
export const SHOW_LEAVE = 'SHOW_LEAVE';
export const SHOW_LEAVE_SUCCESS = 'SHOW_LEAVE_SUCCESS';
export const SHOW_LEAVE_FAILURE = 'SHOW_LEAVE_FAILURE';


export const HANDLE_LEAVE_CHANGE = 'HANDLE_LEAVE_CHANGE';
export const SET_LEAVE_DEFAULTS = 'SET_LEAVE_DEFAULTS';
export const RESET_LEAVE_FIELDS = 'RESET_LEAVE_FIELDS';
export const VALIDATE_LEAVE_FORM='VALIDATE_LEAVE_FORM';