export const LIST_NOTIFICATIONS = 'LIST_NOTIFICATIONS';
export const LIST_NOTIFICATIONS_SUCCESS = 'LIST_NOTIFICATIONS_SUCCESS';
export const LIST_NOTIFICATIONS_FAILURE = 'LIST_NOTIFICATIONS_FAILURE';
export const CREATE_NOTIFICATIONS = 'CREATE_NOTIFICATIONS';
export const CREATE_NOTIFICATIONS_SUCCESS = 'CREATE_NOTIFICATIONS_SUCCESS';
export const CREATE_NOTIFICATIONS_FAILURE = 'CREATE_NOTIFICATIONS_FAILURE';
export const EDIT_NOTIFICATIONS = 'EDIT_NOTIFICATIONS';
export const EDIT_NOTIFICATIONS_SUCCESS = 'EDIT_NOTIFICATIONS_SUCCESS';
export const EDIT_NOTIFICATIONS_FAILURE = 'EDIT_NOTIFICATIONS_FAILURE';
export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const DELETE_NOTIFICATIONS_FAILURE = 'DELETE_NOTIFICATIONS_FAILURE';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SHOW_NOTIFICATION_SUCCESS = 'SHOW_NOTIFICATION_SUCCESS';
export const SHOW_NOTIFICATION_FAILURE = 'SHOW_NOTIFICATION_FAILURE';


export const HANDLE_NOTIFICATION_CHANGE = 'HANDLE_NOTIFICATION_CHANGE';
export const SET_NOTIFICATION_DEFAULTS = 'SET_NOTIFICATION_DEFAULTS';
export const RESET_NOTIFICATION_FIELDS = 'RESET_NOTIFICATION_FIELDS';
export const VALIDATE_NOTIFICATION_FORM='VALIDATE_NOTIFICATION_FORM';