export const LIST_TIMERS = 'LIST_TIMERS';
export const LIST_TIMERS_SUCCESS = 'LIST_TIMERS_SUCCESS';
export const LIST_TIMERS_FAILURE = 'LIST_TIMERS_FAILURE';
export const CREATE_TIMERS = 'CREATE_TIMERS';
export const CREATE_TIMERS_SUCCESS = 'CREATE_TIMERS_SUCCESS';
export const CREATE_TIMERS_FAILURE = 'CREATE_TIMERS_FAILURE';
export const EDIT_TIMERS = 'EDIT_TIMERS';
export const EDIT_TIMERS_SUCCESS = 'EDIT_TIMERS_SUCCESS';
export const EDIT_TIMERS_FAILURE = 'EDIT_TIMERS_FAILURE';
export const DELETE_TIMERS = 'DELETE_TIMERS';
export const DELETE_TIMERS_SUCCESS = 'DELETE_TIMERS_SUCCESS';
export const DELETE_TIMERS_FAILURE = 'DELETE_TIMERS_FAILURE';
export const SHOW_TIMER = 'SHOW_TIMER';
export const SHOW_TIMER_SUCCESS = 'SHOW_TIMER_SUCCESS';
export const SHOW_TIMER_FAILURE = 'SHOW_TIMER_FAILURE';

export const LATEST_SHOW_TIMER = 'LATEST_SHOW_TIMER';
export const LATEST_SHOW_TIMER_SUCCESS = 'LATEST_SHOW_TIMER_SUCCESS';
export const LATEST_SHOW_TIMER_FAILURE = 'LATEST_SHOW_TIMER_FAILURE';


export const HANDLE_TIMER_CHANGE = 'HANDLE_TIMER_CHANGE';
export const SET_TIMER_DEFAULTS = 'SET_TIMER_DEFAULTS';
export const RESET_TIMER_FIELDS = 'RESET_TIMER_FIELDS';
export const VALIDATE_TIMER_FORM='VALIDATE_TIMER_FORM';